# source:      .
# destination: ./_site
# includes:    ./_includes

# collections:
#   projects:
#     output: true


# Analytics
analytics:
  provider               : "google-gtag" 
                          # false (default), "google", "google-universal", "google-gtag", "custom"
  google:
    tracking_id          : "G-KB2H9TFP5B"
    anonymize_ip         : # true, false (default)
